LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake" )
INCLUDE(libcxxopts)

FILE(GLOB EXAMPLE_SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB EXAMPLE_HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(createDeviceExample ${EXAMPLE_SOURCE_FILES} ${EXAMPLE_HEADER_FILES})
TARGET_LINK_LIBRARIES(createDeviceExample fvkcore cxxopts)

ADD_DEPENDENCIES(createDeviceExample fvkcore)