name: Android Build
on:
  push:
  pull_request:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ANDROID_NDK_VERSION: 23.2.8568313

jobs:
  android_build:
    runs-on: ubuntu-latest
    name: "C++ FVKCore - Android"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Configure dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config libfmt-dev libgtest-dev
        sudo apt-get install glslang-tools mesa-vulkan-drivers libvulkan-dev

    - name: Install Android NDK r23
      run: |
        sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;${{env.ANDROID_NDK_VERSION}}'

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build 
    - name: Configure CMake

      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/${{env.ANDROID_NDK_VERSION}}/
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
        -DANDROID_NDK=$ANDROID_NDK_ROOT -DANDROID_ABI="armeabi-v7a"  -DANDROID_PLATFORM=android-16  $GITHUB_WORKSPACE

    - name: Build Library
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE